name: Previo a Playwright Tests Secret
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      plataform: aws
      region: us-east-1
      account: ctaprueba123

      dbhost: ${{secrets.DB_HOST}}
      dbname: ${{secrets.DB_NAME}}
      dbpass: ${{secrets.DB_PASS}}
      dbuser: ${{secrets.DB_USER}}

    runs-on: ubuntu-latest

    # Pasos
    steps:
      - name: "Solo muetsra Mensaje"
        run: echo "Alo alo Mundo, Tudo bem!"

      - name: "Mostrar Variables de entorno"
        run: 
          echo 'Valor de Plataforma:${{ env.plataform }}'
          echo "Valor de Region:${{ env.region }}"
          echo "Valor de account:${{ env.account }}"

          echo "Valores Secretos"

          echo "Valor de Secreto Host:${{env.dbhost}}"
          echo "Valor de Secreto Name:${{env.dbname}}"
          echo "Valor de Secreto User:${{env.dbuser}}"

      - name: "Mostrar Valiables por Defecto"
        run: 
          echo "Evento:${{toJSON(github.event)}}"
          echo "Muesta GitHub_ACTOR:$GITHUB_ACTOR"
          echo "Muesta GitHub_REPOSITORY:$GITHUB_REPOSITORY"
