name: Previo a Playwright Tests
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      plataform: aws
      region: us-east-1
      account: ctaprueba123

    runs-on: ubuntu-latest

    # Pasos
    steps:
      - name: "Solo muetsra Mensaje"
        run: echo "Alo alo Mundo, Tudo bem!"

      - name: "Mostrar Variables de entorno"
        run: 
          echo 'Valor de Plataforma:${{ env.plataform }}'
          echo "Valor de Region:${{ env.region }}"
          echo "Valor de account:${{ env.account }}"

      - name: "Mostrar Valiables por Defecto"
        run: 
          echo "Evento:${{toJSON(github.event)}}"
          echo "Muesta GitHub_ACTOR:$GITHUB_ACTOR"
          echo "Muesta GitHub_REPOSITORY:$GITHUB_REPOSITORY"
