name: Previo a Playwright Tests
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Pasos
    steps:
      - name: "Solo muetsra Mensaje"
        run: echo "Alo alo mUndo, Tudo bem!"
